### ISSUE TITLE
Allow legendgram to use matplotlib custom palette

### ISSUE THREAD

**Issue by lenkahas** [pysal/legendgram#12]
I wanted to use very simple custom made palette from matplotlib 

`pal = ListedColormap(['#829DED','#D9E4FC','#E9EFFE','#F0F6FF','#FFFFFF','#FFFFFF','#FFF1F0','#FFDDDC','#FFC8C8','#FD5E5E'])`

The only issue with that was that the legendgram have defined number of colors as `pal.number` but in ListedColormap has the same as `pal.N`.

Could you expand the code for this option?

**Comment by martinfleis** [comment]
This should already work on master as we implemented it in #10.
